#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_let = 1,
  anon_sym_EQ = 2,
  anon_sym_SEMI = 3,
  anon_sym_AT = 4,
  anon_sym_LPAREN = 5,
  anon_sym_COMMA = 6,
  anon_sym_RPAREN = 7,
  anon_sym_if = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_else = 11,
  anon_sym_loop = 12,
  anon_sym_LOOP = 13,
  anon_sym_loop_end = 14,
  sym_break_statement = 15,
  sym_continue_statement = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_STAR = 19,
  anon_sym_SLASH = 20,
  anon_sym_CARET = 21,
  sym_identifier = 22,
  sym_number = 23,
  sym_source_file = 24,
  sym_statement = 25,
  sym_variable_assignment = 26,
  sym_function_call = 27,
  sym_conditional_statement = 28,
  sym_loop_statement = 29,
  sym_print_statement = 30,
  sym_expression = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_function_call_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_if] = "if",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_else] = "else",
  [anon_sym_loop] = "loop",
  [anon_sym_LOOP] = "LOOP",
  [anon_sym_loop_end] = "loop_end",
  [sym_break_statement] = "break_statement",
  [sym_continue_statement] = "continue_statement",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_CARET] = "^",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_variable_assignment] = "variable_assignment",
  [sym_function_call] = "function_call",
  [sym_conditional_statement] = "conditional_statement",
  [sym_loop_statement] = "loop_statement",
  [sym_print_statement] = "print_statement",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_LOOP] = anon_sym_LOOP,
  [anon_sym_loop_end] = anon_sym_loop_end,
  [sym_break_statement] = sym_break_statement,
  [sym_continue_statement] = sym_continue_statement,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_CARET] = anon_sym_CARET,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_variable_assignment] = sym_variable_assignment,
  [sym_function_call] = sym_function_call,
  [sym_conditional_statement] = sym_conditional_statement,
  [sym_loop_statement] = sym_loop_statement,
  [sym_print_statement] = sym_print_statement,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LOOP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop_end] = {
    .visible = true,
    .named = false,
  },
  [sym_break_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_continue_statement] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 4,
  [12] = 7,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 15,
  [19] = 9,
  [20] = 14,
  [21] = 8,
  [22] = 13,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 24,
  [28] = 23,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 35,
  [39] = 29,
  [40] = 30,
  [41] = 33,
  [42] = 37,
  [43] = 26,
  [44] = 36,
  [45] = 34,
  [46] = 25,
  [47] = 31,
  [48] = 32,
  [49] = 49,
  [50] = 49,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 53,
  [55] = 52,
  [56] = 56,
  [57] = 56,
  [58] = 58,
  [59] = 59,
  [60] = 58,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 61,
  [66] = 59,
  [67] = 67,
  [68] = 62,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 70,
  [73] = 73,
  [74] = 74,
  [75] = 73,
  [76] = 76,
  [77] = 77,
  [78] = 77,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 81,
  [83] = 80,
  [84] = 84,
  [85] = 71,
  [86] = 86,
  [87] = 86,
  [88] = 69,
  [89] = 74,
  [90] = 84,
  [91] = 76,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '(', 36,
        ')', 38,
        '*', 51,
        '+', 49,
        ',', 37,
        '-', 50,
        '/', 52,
        ';', 34,
        '=', 33,
        '@', 35,
        'L', 3,
        '^', 53,
        'b', 25,
        'c', 20,
        'e', 16,
        'i', 13,
        'l', 7,
        '{', 40,
        '}', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 2:
      if (lookahead == 'O') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'O') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == 'P') ADVANCE(45);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(46);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'k') ADVANCE(47);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(44);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(43);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        ';', 34,
        '@', 35,
        'L', 3,
        'b', 25,
        'c', 20,
        'e', 16,
        'i', 13,
        'l', 8,
        '}', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_loop);
      if (lookahead == '_') ADVANCE(12);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LOOP);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_loop_end);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_break_statement);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_continue_statement);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 30},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 30},
  [10] = {.lex_state = 30},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 30},
  [13] = {.lex_state = 30},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 30},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 30},
  [18] = {.lex_state = 30},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 30},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 30},
  [23] = {.lex_state = 30},
  [24] = {.lex_state = 30},
  [25] = {.lex_state = 30},
  [26] = {.lex_state = 30},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 30},
  [30] = {.lex_state = 30},
  [31] = {.lex_state = 30},
  [32] = {.lex_state = 30},
  [33] = {.lex_state = 30},
  [34] = {.lex_state = 30},
  [35] = {.lex_state = 30},
  [36] = {.lex_state = 30},
  [37] = {.lex_state = 30},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_LOOP] = ACTIONS(1),
    [anon_sym_loop_end] = ACTIONS(1),
    [sym_break_statement] = ACTIONS(1),
    [sym_continue_statement] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(79),
    [sym_statement] = STATE(10),
    [sym_variable_assignment] = STATE(36),
    [sym_function_call] = STATE(36),
    [sym_conditional_statement] = STATE(36),
    [sym_loop_statement] = STATE(36),
    [sym_print_statement] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_loop] = ACTIONS(13),
    [anon_sym_LOOP] = ACTIONS(13),
    [sym_break_statement] = ACTIONS(15),
    [sym_continue_statement] = ACTIONS(15),
  },
  [2] = {
    [sym_statement] = STATE(8),
    [sym_variable_assignment] = STATE(44),
    [sym_function_call] = STATE(44),
    [sym_conditional_statement] = STATE(44),
    [sym_loop_statement] = STATE(44),
    [sym_print_statement] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_let] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(19),
    [anon_sym_AT] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_loop] = ACTIONS(25),
    [anon_sym_LOOP] = ACTIONS(27),
    [anon_sym_loop_end] = ACTIONS(29),
    [sym_break_statement] = ACTIONS(31),
    [sym_continue_statement] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(33),
    [anon_sym_DASH] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(33),
  },
  [3] = {
    [sym_statement] = STATE(21),
    [sym_variable_assignment] = STATE(44),
    [sym_function_call] = STATE(44),
    [sym_conditional_statement] = STATE(44),
    [sym_loop_statement] = STATE(44),
    [sym_print_statement] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(21),
    [anon_sym_let] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(19),
    [anon_sym_AT] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_loop] = ACTIONS(25),
    [anon_sym_LOOP] = ACTIONS(27),
    [anon_sym_loop_end] = ACTIONS(35),
    [sym_break_statement] = ACTIONS(31),
    [sym_continue_statement] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(33),
    [anon_sym_DASH] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(39), 1,
      anon_sym_let,
    ACTIONS(42), 1,
      anon_sym_SEMI,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(48), 1,
      anon_sym_if,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(51), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(54), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(4), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [36] = 2,
    ACTIONS(59), 1,
      anon_sym_loop,
    ACTIONS(57), 16,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_if,
      anon_sym_LBRACE,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
  [58] = 2,
    ACTIONS(63), 1,
      anon_sym_loop,
    ACTIONS(61), 16,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_if,
      anon_sym_LBRACE,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
  [80] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(4), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [115] = 10,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_SEMI,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_loop,
    ACTIONS(27), 1,
      anon_sym_LOOP,
    ACTIONS(67), 1,
      anon_sym_loop_end,
    ACTIONS(31), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(11), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(44), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [152] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(13), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [187] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(4), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [222] = 10,
    ACTIONS(37), 1,
      anon_sym_loop_end,
    ACTIONS(73), 1,
      anon_sym_let,
    ACTIONS(76), 1,
      anon_sym_SEMI,
    ACTIONS(79), 1,
      anon_sym_AT,
    ACTIONS(82), 1,
      anon_sym_if,
    ACTIONS(85), 1,
      anon_sym_loop,
    ACTIONS(88), 1,
      anon_sym_LOOP,
    ACTIONS(91), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(11), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(44), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [259] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(4), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [294] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(4), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [329] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(7), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [364] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(16), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [399] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(4), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [434] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(4), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [469] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(17), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [504] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(22), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [539] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(12), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [574] = 10,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_SEMI,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_loop,
    ACTIONS(27), 1,
      anon_sym_LOOP,
    ACTIONS(108), 1,
      anon_sym_loop_end,
    ACTIONS(31), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(11), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(44), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [611] = 9,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_loop,
      anon_sym_LOOP,
    ACTIONS(15), 2,
      sym_break_statement,
      sym_continue_statement,
    STATE(4), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(36), 5,
      sym_variable_assignment,
      sym_function_call,
      sym_conditional_statement,
      sym_loop_statement,
      sym_print_statement,
  [646] = 2,
    ACTIONS(114), 1,
      anon_sym_else,
    ACTIONS(112), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [662] = 2,
    ACTIONS(118), 1,
      anon_sym_else,
    ACTIONS(116), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [678] = 1,
    ACTIONS(120), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [691] = 1,
    ACTIONS(122), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [704] = 3,
    ACTIONS(124), 1,
      anon_sym_else,
    ACTIONS(126), 1,
      anon_sym_loop,
    ACTIONS(116), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [721] = 3,
    ACTIONS(128), 1,
      anon_sym_else,
    ACTIONS(130), 1,
      anon_sym_loop,
    ACTIONS(112), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [738] = 1,
    ACTIONS(132), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [751] = 1,
    ACTIONS(134), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [764] = 1,
    ACTIONS(136), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [777] = 1,
    ACTIONS(138), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [790] = 1,
    ACTIONS(140), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [803] = 1,
    ACTIONS(142), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [816] = 1,
    ACTIONS(144), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [829] = 1,
    ACTIONS(146), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [842] = 1,
    ACTIONS(148), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_loop,
      anon_sym_LOOP,
      sym_break_statement,
      sym_continue_statement,
  [855] = 2,
    ACTIONS(150), 1,
      anon_sym_loop,
    ACTIONS(144), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [869] = 2,
    ACTIONS(152), 1,
      anon_sym_loop,
    ACTIONS(132), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [883] = 2,
    ACTIONS(154), 1,
      anon_sym_loop,
    ACTIONS(134), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [897] = 2,
    ACTIONS(156), 1,
      anon_sym_loop,
    ACTIONS(140), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [911] = 2,
    ACTIONS(158), 1,
      anon_sym_loop,
    ACTIONS(148), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [925] = 2,
    ACTIONS(160), 1,
      anon_sym_loop,
    ACTIONS(122), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [939] = 2,
    ACTIONS(162), 1,
      anon_sym_loop,
    ACTIONS(146), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [953] = 2,
    ACTIONS(164), 1,
      anon_sym_loop,
    ACTIONS(142), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [967] = 2,
    ACTIONS(166), 1,
      anon_sym_loop,
    ACTIONS(120), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [981] = 2,
    ACTIONS(168), 1,
      anon_sym_loop,
    ACTIONS(136), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [995] = 2,
    ACTIONS(170), 1,
      anon_sym_loop,
    ACTIONS(138), 8,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_if,
      anon_sym_LOOP,
      anon_sym_loop_end,
      sym_break_statement,
      sym_continue_statement,
  [1009] = 4,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(33), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
  [1026] = 4,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(33), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
  [1043] = 2,
    ACTIONS(178), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(33), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
  [1055] = 2,
    ACTIONS(180), 1,
      anon_sym_SEMI,
    ACTIONS(33), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
  [1066] = 2,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
  [1077] = 2,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
  [1088] = 2,
    ACTIONS(186), 1,
      anon_sym_SEMI,
    ACTIONS(33), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
  [1099] = 3,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_expression,
    ACTIONS(190), 2,
      sym_identifier,
      sym_number,
  [1110] = 3,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      sym_expression,
    ACTIONS(190), 2,
      sym_identifier,
      sym_number,
  [1121] = 2,
    STATE(54), 1,
      sym_expression,
    ACTIONS(190), 2,
      sym_identifier,
      sym_number,
  [1129] = 2,
    STATE(3), 1,
      sym_expression,
    ACTIONS(190), 2,
      sym_identifier,
      sym_number,
  [1137] = 2,
    STATE(53), 1,
      sym_expression,
    ACTIONS(190), 2,
      sym_identifier,
      sym_number,
  [1145] = 2,
    STATE(55), 1,
      sym_expression,
    ACTIONS(190), 2,
      sym_identifier,
      sym_number,
  [1153] = 3,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_function_call_repeat1,
  [1163] = 2,
    STATE(51), 1,
      sym_expression,
    ACTIONS(190), 2,
      sym_identifier,
      sym_number,
  [1171] = 3,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_function_call_repeat1,
  [1181] = 2,
    STATE(52), 1,
      sym_expression,
    ACTIONS(190), 2,
      sym_identifier,
      sym_number,
  [1189] = 2,
    STATE(2), 1,
      sym_expression,
    ACTIONS(190), 2,
      sym_identifier,
      sym_number,
  [1197] = 2,
    STATE(6), 1,
      sym_expression,
    ACTIONS(190), 2,
      sym_identifier,
      sym_number,
  [1205] = 3,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_function_call_repeat1,
  [1215] = 1,
    ACTIONS(201), 1,
      anon_sym_EQ,
  [1219] = 1,
    ACTIONS(203), 1,
      anon_sym_SEMI,
  [1223] = 1,
    ACTIONS(205), 1,
      anon_sym_LBRACE,
  [1227] = 1,
    ACTIONS(207), 1,
      anon_sym_SEMI,
  [1231] = 1,
    ACTIONS(209), 1,
      anon_sym_SEMI,
  [1235] = 1,
    ACTIONS(211), 1,
      anon_sym_LPAREN,
  [1239] = 1,
    ACTIONS(213), 1,
      anon_sym_SEMI,
  [1243] = 1,
    ACTIONS(215), 1,
      sym_identifier,
  [1247] = 1,
    ACTIONS(217), 1,
      sym_identifier,
  [1251] = 1,
    ACTIONS(219), 1,
      sym_identifier,
  [1255] = 1,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
  [1259] = 1,
    ACTIONS(223), 1,
      anon_sym_SEMI,
  [1263] = 1,
    ACTIONS(225), 1,
      anon_sym_SEMI,
  [1267] = 1,
    ACTIONS(227), 1,
      anon_sym_SEMI,
  [1271] = 1,
    ACTIONS(229), 1,
      anon_sym_SEMI,
  [1275] = 1,
    ACTIONS(231), 1,
      sym_identifier,
  [1279] = 1,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
  [1283] = 1,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
  [1287] = 1,
    ACTIONS(237), 1,
      anon_sym_LBRACE,
  [1291] = 1,
    ACTIONS(239), 1,
      anon_sym_EQ,
  [1295] = 1,
    ACTIONS(241), 1,
      anon_sym_LPAREN,
  [1299] = 1,
    ACTIONS(243), 1,
      sym_identifier,
  [1303] = 1,
    ACTIONS(245), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 36,
  [SMALL_STATE(6)] = 58,
  [SMALL_STATE(7)] = 80,
  [SMALL_STATE(8)] = 115,
  [SMALL_STATE(9)] = 152,
  [SMALL_STATE(10)] = 187,
  [SMALL_STATE(11)] = 222,
  [SMALL_STATE(12)] = 259,
  [SMALL_STATE(13)] = 294,
  [SMALL_STATE(14)] = 329,
  [SMALL_STATE(15)] = 364,
  [SMALL_STATE(16)] = 399,
  [SMALL_STATE(17)] = 434,
  [SMALL_STATE(18)] = 469,
  [SMALL_STATE(19)] = 504,
  [SMALL_STATE(20)] = 539,
  [SMALL_STATE(21)] = 574,
  [SMALL_STATE(22)] = 611,
  [SMALL_STATE(23)] = 646,
  [SMALL_STATE(24)] = 662,
  [SMALL_STATE(25)] = 678,
  [SMALL_STATE(26)] = 691,
  [SMALL_STATE(27)] = 704,
  [SMALL_STATE(28)] = 721,
  [SMALL_STATE(29)] = 738,
  [SMALL_STATE(30)] = 751,
  [SMALL_STATE(31)] = 764,
  [SMALL_STATE(32)] = 777,
  [SMALL_STATE(33)] = 790,
  [SMALL_STATE(34)] = 803,
  [SMALL_STATE(35)] = 816,
  [SMALL_STATE(36)] = 829,
  [SMALL_STATE(37)] = 842,
  [SMALL_STATE(38)] = 855,
  [SMALL_STATE(39)] = 869,
  [SMALL_STATE(40)] = 883,
  [SMALL_STATE(41)] = 897,
  [SMALL_STATE(42)] = 911,
  [SMALL_STATE(43)] = 925,
  [SMALL_STATE(44)] = 939,
  [SMALL_STATE(45)] = 953,
  [SMALL_STATE(46)] = 967,
  [SMALL_STATE(47)] = 981,
  [SMALL_STATE(48)] = 995,
  [SMALL_STATE(49)] = 1009,
  [SMALL_STATE(50)] = 1026,
  [SMALL_STATE(51)] = 1043,
  [SMALL_STATE(52)] = 1055,
  [SMALL_STATE(53)] = 1066,
  [SMALL_STATE(54)] = 1077,
  [SMALL_STATE(55)] = 1088,
  [SMALL_STATE(56)] = 1099,
  [SMALL_STATE(57)] = 1110,
  [SMALL_STATE(58)] = 1121,
  [SMALL_STATE(59)] = 1129,
  [SMALL_STATE(60)] = 1137,
  [SMALL_STATE(61)] = 1145,
  [SMALL_STATE(62)] = 1153,
  [SMALL_STATE(63)] = 1163,
  [SMALL_STATE(64)] = 1171,
  [SMALL_STATE(65)] = 1181,
  [SMALL_STATE(66)] = 1189,
  [SMALL_STATE(67)] = 1197,
  [SMALL_STATE(68)] = 1205,
  [SMALL_STATE(69)] = 1215,
  [SMALL_STATE(70)] = 1219,
  [SMALL_STATE(71)] = 1223,
  [SMALL_STATE(72)] = 1227,
  [SMALL_STATE(73)] = 1231,
  [SMALL_STATE(74)] = 1235,
  [SMALL_STATE(75)] = 1239,
  [SMALL_STATE(76)] = 1243,
  [SMALL_STATE(77)] = 1247,
  [SMALL_STATE(78)] = 1251,
  [SMALL_STATE(79)] = 1255,
  [SMALL_STATE(80)] = 1259,
  [SMALL_STATE(81)] = 1263,
  [SMALL_STATE(82)] = 1267,
  [SMALL_STATE(83)] = 1271,
  [SMALL_STATE(84)] = 1275,
  [SMALL_STATE(85)] = 1279,
  [SMALL_STATE(86)] = 1283,
  [SMALL_STATE(87)] = 1287,
  [SMALL_STATE(88)] = 1291,
  [SMALL_STATE(89)] = 1295,
  [SMALL_STATE(90)] = 1299,
  [SMALL_STATE(91)] = 1303,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_statement, 5, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_statement, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_statement, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 6, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_statement, 4, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_statement, 5, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_statement, 9, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_statement, 8, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_statement, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_assignment, 5, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_statement, 7, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 7, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_statement, 7, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_statement, 9, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_statement, 8, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 7, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 6, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_statement, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_statement, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_statement, 4, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_assignment, 5, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [221] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_maths_lang_grammar(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
